//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityGoodTaste.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityGoodTaste.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageCheck.
        /// </summary>
        public static string AverageCheck {
            get {
                return ResourceManager.GetString("AverageCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityName.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseHourName.
        /// </summary>
        public static string CloseHourName {
            get {
                return ResourceManager.GetString("CloseHourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT INFO.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CousineName.
        /// </summary>
        public static string CousineName {
            get {
                return ResourceManager.GetString("CousineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisine.
        /// </summary>
        public static string Cuisine {
            get {
                return ResourceManager.GetString("Cuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisines.
        /// </summary>
        public static string Cuisines {
            get {
                return ResourceManager.GetString("Cuisines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventDescription.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventEndDate.
        /// </summary>
        public static string EventEndDate {
            get {
                return ResourceManager.GetString("EventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventName.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventStartDate.
        /// </summary>
        public static string EventStartDate {
            get {
                return ResourceManager.GetString("EventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventTypeName.
        /// </summary>
        public static string EventTypeName {
            get {
                return ResourceManager.GetString("EventTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event types.
        /// </summary>
        public static string EventTypes {
            get {
                return ResourceManager.GetString("EventTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InDoor.
        /// </summary>
        public static string InDoor {
            get {
                return ResourceManager.GetString("InDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InformationAboutRestaurant.
        /// </summary>
        public static string InformationAboutRestaurant {
            get {
                return ResourceManager.GetString("InformationAboutRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsShowMenu.
        /// </summary>
        public static string IsShowMenu {
            get {
                return ResourceManager.GetString("IsShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeReserv.
        /// </summary>
        public static string MakeReserv {
            get {
                return ResourceManager.GetString("MakeReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealDescription.
        /// </summary>
        public static string MealDescription {
            get {
                return ResourceManager.GetString("MealDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealGroup.
        /// </summary>
        public static string MealGroup {
            get {
                return ResourceManager.GetString("MealGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealGroupName.
        /// </summary>
        public static string MealGroupName {
            get {
                return ResourceManager.GetString("MealGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealGroups.
        /// </summary>
        public static string MealGroups {
            get {
                return ResourceManager.GetString("MealGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealName.
        /// </summary>
        public static string MealName {
            get {
                return ResourceManager.GetString("MealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MealPrice.
        /// </summary>
        public static string MealPrice {
            get {
                return ResourceManager.GetString("MealPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MealsMenu {
            get {
                return ResourceManager.GetString("MealsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenHourName.
        /// </summary>
        public static string OpenHourName {
            get {
                return ResourceManager.GetString("OpenHourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDate.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneName.
        /// </summary>
        public static string PhoneName {
            get {
                return ResourceManager.GetString("PhoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoPath.
        /// </summary>
        public static string PhotoPath {
            get {
                return ResourceManager.GetString("PhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceEntries.
        /// </summary>
        public static string PriceEntries {
            get {
                return ResourceManager.GetString("PriceEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended restaurants.
        /// </summary>
        public static string RecommendedRestaurants {
            get {
                return ResourceManager.GetString("RecommendedRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserv.
        /// </summary>
        public static string Reserv {
            get {
                return ResourceManager.GetString("Reserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestarauntGroupName.
        /// </summary>
        public static string RestarauntGroupName {
            get {
                return ResourceManager.GetString("RestarauntGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantAddress.
        /// </summary>
        public static string RestaurantAddress {
            get {
                return ResourceManager.GetString("RestaurantAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantEvent.
        /// </summary>
        public static string RestaurantEvent {
            get {
                return ResourceManager.GetString("RestaurantEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantFeatureName.
        /// </summary>
        public static string RestaurantFeatureName {
            get {
                return ResourceManager.GetString("RestaurantFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantFeatures.
        /// </summary>
        public static string RestaurantFeatures {
            get {
                return ResourceManager.GetString("RestaurantFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantName.
        /// </summary>
        public static string RestaurantName {
            get {
                return ResourceManager.GetString("RestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantPhoneNumber.
        /// </summary>
        public static string RestaurantPhoneNumber {
            get {
                return ResourceManager.GetString("RestaurantPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string RestaurantReview {
            get {
                return ResourceManager.GetString("RestaurantReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Restaurants {
            get {
                return ResourceManager.GetString("Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantSchema.
        /// </summary>
        public static string RestaurantSchema {
            get {
                return ResourceManager.GetString("RestaurantSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantSchemaName.
        /// </summary>
        public static string RestaurantSchemaName {
            get {
                return ResourceManager.GetString("RestaurantSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantSchemas.
        /// </summary>
        public static string RestaurantSchemas {
            get {
                return ResourceManager.GetString("RestaurantSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantsGroup.
        /// </summary>
        public static string RestaurantsGroup {
            get {
                return ResourceManager.GetString("RestaurantsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewDate.
        /// </summary>
        public static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewText.
        /// </summary>
        public static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurant name, kitchen, menu item.
        /// </summary>
        public static string SearchRestmMess {
            get {
                return ResourceManager.GetString("SearchRestmMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats .
        /// </summary>
        public static string SeatsCount {
            get {
                return ResourceManager.GetString("SeatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE.
        /// </summary>
        public static string SelectTable {
            get {
                return ResourceManager.GetString("SelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Assistant.
        /// </summary>
        public static string SmartAssistant {
            get {
                return ResourceManager.GetString("SmartAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmokingZone.
        /// </summary>
        public static string SmokingZone {
            get {
                return ResourceManager.GetString("SmokingZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialWorkHours.
        /// </summary>
        public static string SpecialWorkHours {
            get {
                return ResourceManager.GetString("SpecialWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubMenuName.
        /// </summary>
        public static string SubMenuName {
            get {
                return ResourceManager.GetString("SubMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table number.
        /// </summary>
        public static string TableNumber {
            get {
                return ResourceManager.GetString("TableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableReserved.
        /// </summary>
        public static string TableReserved {
            get {
                return ResourceManager.GetString("TableReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSurname.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkDate.
        /// </summary>
        public static string WorkDate {
            get {
                return ResourceManager.GetString("WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkHours.
        /// </summary>
        public static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сurrency.
        /// </summary>
        public static string Сurrency {
            get {
                return ResourceManager.GetString("Сurrency", resourceCulture);
            }
        }
    }
}
